### ISSUE TITLE
    return '%s#%i %s' % (coin, *be.get_latest(coin))

### ISSUE THREAD

**Issue by asciitohex** [sebastianst/GenesisZ#2] opened 2017-08-31 10:16 UTC
./genesis.py  with options 

```
File "./genesis.py", line 161
    return '%s#%i %s' % (coin, *be.get_latest(coin))
                               ^
SyntaxError: invalid syntax
```

**Comment by sebastianst** [comment] 2017-08-31 15:03
What python version do you use? I use 3.6.2. Your version seems to not know the unpacking operator `*`.
Also please pull my latest commit, which fixes the zcash api call in `blockexplorer.py`

**Comment by asciitohex** [comment] 2017-08-31 19:38
thank you sebastianst, my python version is 3.6.2 also in virtualenv
I will pull latest commit soon

**Comment by GianniExplore** [comment] 2017-08-31 19:40
what disto did you use?

**Comment by asciitohex** [comment] 2017-09-25 16:54
(GenesisZ) root@ubuntu:~/GenesisZ# ./genesis.py -s "/root/silentarmy/sa-solver --nonces 4000 -i" -t 1477641360
Traceback (most recent call last):
  File "./genesis.py", line 231, in <module>
    main()
  File "./genesis.py", line 29, in main
    eh = buildEquihashInputHeader(args)
  File "./genesis.py", line 146, in buildEquihashInputHeader
    txhash = tx.GetHash()
  File "/root/GenesisZ/local/lib/python3.5/site-packages/bitcoin/core/__init__.py", line 404, in GetHash
    raise AttributeError("CMutableTransaction.GetHash() has been removed; use GetTxid() instead")
AttributeError: CMutableTransaction.GetHash() has been removed; use GetTxid() instead

**Comment by sebastianst** [comment] 2017-11-03 11:12
Looks like this is related to the API changes in the bitcoin module. Closing this in favor of #4

**Closed as completed by sebastianst** 2017-11-03 11:12 UTC

**Comment by sebastianst** [comment] 2018-05-10 21:08
I just did a fresh checkout of GenesisZ and silentarmy and cannot reproduce this error.
```
# pip freeze
certifi==2018.4.16
chardet==3.0.4
idna==2.6
pyblake2==1.1.2
python-bitcoinlib==0.10.1
requests==2.18.4
urllib3==1.22
```
